name: analytics
version: "1.0.0"

profile: analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

seeds:
  analytics:
    seed_electricity_rate:
      +column_types:
        fiscal_year: integer
        rate_category: varchar
        electricity_rate_yen_per_kwh: float
        valid_from: date
        valid_to: date
    seed_co2_emission_factor:
      +column_types:
        fiscal_year: integer
        provider: varchar
        co2_factor_t_per_kwh: float
        valid_from: date
        valid_to: date

models:
  analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
      intermediate:
        +materialized: view
