analytics:
  target: snowflake_dev
  outputs:
    snowflake_dev:
      type: snowflake
      role: ACCOUNTADMIN
      database: TOKYOPOWER_ANALYTICS
      warehouse: PC_DBT_WH
      schema: public
      threads: 4
    snowflake_prod:
      type: snowflake
      role: ACCOUNTADMIN
      database: TOKYOPOWER_ANALYTICS_PROD
      warehouse: PC_DBT_WH
      schema: public
      threads: 4
