analytics:
  target: snowflake_dev
  outputs:
    snowflake_dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: TOKYOPOWER_ANALYTICS
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'PC_DBT_WH') }}"
      schema: public
      threads: 4
    snowflake_prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: TOKYOPOWER_ANALYTICS_PROD
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'PC_DBT_WH') }}"
      schema: public
      threads: 4
